package com.depression.model;

import java.util.Date;

public class Article extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.category_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.type_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.title
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.digest
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private String digest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.hits
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long hits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.collection_num
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long collectionNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.author
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.source
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.thumbnail
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private String thumbnail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.create_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.modify_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.share
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Integer share;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.release_from
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Long releaseFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.is_enable
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Byte isEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.is_delete
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	private Byte isDelete;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_id
	 * @return  the value of article.article_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_id
	 * @param articleId  the value for article.article_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setArticleId(Long articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.category_id
	 * @return  the value of article.category_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.category_id
	 * @param categoryId  the value for article.category_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.type_id
	 * @return  the value of article.type_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.type_id
	 * @param typeId  the value for article.type_id
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.title
	 * @return  the value of article.title
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.title
	 * @param title  the value for article.title
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.digest
	 * @return  the value of article.digest
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public String getDigest() {
		return digest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.digest
	 * @param digest  the value for article.digest
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setDigest(String digest) {
		this.digest = digest == null ? null : digest.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.hits
	 * @return  the value of article.hits
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getHits() {
		return hits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.hits
	 * @param hits  the value for article.hits
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setHits(Long hits) {
		this.hits = hits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.collection_num
	 * @return  the value of article.collection_num
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getCollectionNum() {
		return collectionNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.collection_num
	 * @param collectionNum  the value for article.collection_num
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setCollectionNum(Long collectionNum) {
		this.collectionNum = collectionNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.author
	 * @return  the value of article.author
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.author
	 * @param author  the value for article.author
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.source
	 * @return  the value of article.source
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.source
	 * @param source  the value for article.source
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.thumbnail
	 * @return  the value of article.thumbnail
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public String getThumbnail() {
		return thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.thumbnail
	 * @param thumbnail  the value for article.thumbnail
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail == null ? null : thumbnail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.create_time
	 * @return  the value of article.create_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.create_time
	 * @param createTime  the value for article.create_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.modify_time
	 * @return  the value of article.modify_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.modify_time
	 * @param modifyTime  the value for article.modify_time
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.share
	 * @return  the value of article.share
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Integer getShare() {
		return share;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.share
	 * @param share  the value for article.share
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setShare(Integer share) {
		this.share = share;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.release_from
	 * @return  the value of article.release_from
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Long getReleaseFrom() {
		return releaseFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.release_from
	 * @param releaseFrom  the value for article.release_from
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setReleaseFrom(Long releaseFrom) {
		this.releaseFrom = releaseFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.is_enable
	 * @return  the value of article.is_enable
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Byte getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.is_enable
	 * @param isEnable  the value for article.is_enable
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setIsEnable(Byte isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.is_delete
	 * @return  the value of article.is_delete
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public Byte getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.is_delete
	 * @param isDelete  the value for article.is_delete
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}
}