package com.depression.model;

public class CapitalCommissionRate extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_commission_rate.crid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Long crid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_commission_rate.type
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment(类型：11 倾述佣金，12 咨询佣金) */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_commission_rate.rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment(倾述佣金比例0-100) */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_commission_rate.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_commission_rate.crid
     *
     * @return the value of capital_commission_rate.crid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Long getCrid() {
        return crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_commission_rate.crid
     *
     * @param crid the value for capital_commission_rate.crid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setCrid(Long crid) {
        this.crid = crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_commission_rate.type
     *
     * @return the value of capital_commission_rate.type
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_commission_rate.type
     *
     * @param type the value for capital_commission_rate.type
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_commission_rate.rate
     *
     * @return the value of capital_commission_rate.rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_commission_rate.rate
     *
     * @param rate the value for capital_commission_rate.rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_commission_rate.is_delete
     *
     * @return the value of capital_commission_rate.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_commission_rate.is_delete
     *
     * @param isDelete the value for capital_commission_rate.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}