package com.depression.model;

import java.math.BigDecimal;
import java.util.Date;

public class CapitalWithdrawRequest extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.wrid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Long wrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.mid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment(主键) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.no
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.request_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.audit_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.auditor
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private String auditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.channel
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment(0 微信，1银联) */
    private Byte channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.account
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.amount
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.status
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment(0 未审核，1已审核) */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_withdraw_request.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    /* @Comment() */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.wrid
     *
     * @return the value of capital_withdraw_request.wrid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Long getWrid() {
        return wrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.wrid
     *
     * @param wrid the value for capital_withdraw_request.wrid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setWrid(Long wrid) {
        this.wrid = wrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.mid
     *
     * @return the value of capital_withdraw_request.mid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.mid
     *
     * @param mid the value for capital_withdraw_request.mid
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.no
     *
     * @return the value of capital_withdraw_request.no
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.no
     *
     * @param no the value for capital_withdraw_request.no
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.request_time
     *
     * @return the value of capital_withdraw_request.request_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.request_time
     *
     * @param requestTime the value for capital_withdraw_request.request_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.audit_time
     *
     * @return the value of capital_withdraw_request.audit_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.audit_time
     *
     * @param auditTime the value for capital_withdraw_request.audit_time
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.auditor
     *
     * @return the value of capital_withdraw_request.auditor
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.auditor
     *
     * @param auditor the value for capital_withdraw_request.auditor
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.channel
     *
     * @return the value of capital_withdraw_request.channel
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.channel
     *
     * @param channel the value for capital_withdraw_request.channel
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.account
     *
     * @return the value of capital_withdraw_request.account
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.account
     *
     * @param account the value for capital_withdraw_request.account
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.amount
     *
     * @return the value of capital_withdraw_request.amount
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.amount
     *
     * @param amount the value for capital_withdraw_request.amount
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.status
     *
     * @return the value of capital_withdraw_request.status
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.status
     *
     * @param status the value for capital_withdraw_request.status
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_withdraw_request.is_delete
     *
     * @return the value of capital_withdraw_request.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_withdraw_request.is_delete
     *
     * @param isDelete the value for capital_withdraw_request.is_delete
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}