package com.depression.model;

import java.util.Date;

public class MemberTemp extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_temp.mid
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    /* @Comment() */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_temp.create_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    /* @Comment() */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_temp.delete_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    /* @Comment() */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_temp.is_delete
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    /* @Comment() */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_temp.mid
     *
     * @return the value of member_temp.mid
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_temp.mid
     *
     * @param mid the value for member_temp.mid
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_temp.create_time
     *
     * @return the value of member_temp.create_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_temp.create_time
     *
     * @param createTime the value for member_temp.create_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_temp.delete_time
     *
     * @return the value of member_temp.delete_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_temp.delete_time
     *
     * @param deleteTime the value for member_temp.delete_time
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_temp.is_delete
     *
     * @return the value of member_temp.is_delete
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_temp.is_delete
     *
     * @param isDelete the value for member_temp.is_delete
     *
     * @mbggenerated Fri Dec 30 10:34:18 CST 2016
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}