package com.depression.model;

import java.util.Date;

public class MemberAdvisory extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.advisory_id
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Long advisoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.mid
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Long mid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.title
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.content
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.write_location
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private String writeLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.is_anony
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Byte isAnony;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.read_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Integer readCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.share_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Integer shareCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.is_recommended
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Byte isRecommended;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.create_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.modify_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.order_factor
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Integer orderFactor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.release_from
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Long releaseFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory.is_delete
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	private Byte isDelete;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.advisory_id
	 * @return  the value of member_advisory.advisory_id
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Long getAdvisoryId() {
		return advisoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.advisory_id
	 * @param advisoryId  the value for member_advisory.advisory_id
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setAdvisoryId(Long advisoryId) {
		this.advisoryId = advisoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.mid
	 * @return  the value of member_advisory.mid
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Long getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.mid
	 * @param mid  the value for member_advisory.mid
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setMid(Long mid) {
		this.mid = mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.title
	 * @return  the value of member_advisory.title
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.title
	 * @param title  the value for member_advisory.title
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.content
	 * @return  the value of member_advisory.content
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.content
	 * @param content  the value for member_advisory.content
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.write_location
	 * @return  the value of member_advisory.write_location
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public String getWriteLocation() {
		return writeLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.write_location
	 * @param writeLocation  the value for member_advisory.write_location
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setWriteLocation(String writeLocation) {
		this.writeLocation = writeLocation == null ? null : writeLocation
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.is_anony
	 * @return  the value of member_advisory.is_anony
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Byte getIsAnony() {
		return isAnony;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.is_anony
	 * @param isAnony  the value for member_advisory.is_anony
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setIsAnony(Byte isAnony) {
		this.isAnony = isAnony;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.read_count
	 * @return  the value of member_advisory.read_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Integer getReadCount() {
		return readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.read_count
	 * @param readCount  the value for member_advisory.read_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setReadCount(Integer readCount) {
		this.readCount = readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.share_count
	 * @return  the value of member_advisory.share_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Integer getShareCount() {
		return shareCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.share_count
	 * @param shareCount  the value for member_advisory.share_count
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setShareCount(Integer shareCount) {
		this.shareCount = shareCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.is_recommended
	 * @return  the value of member_advisory.is_recommended
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Byte getIsRecommended() {
		return isRecommended;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.is_recommended
	 * @param isRecommended  the value for member_advisory.is_recommended
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setIsRecommended(Byte isRecommended) {
		this.isRecommended = isRecommended;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.create_time
	 * @return  the value of member_advisory.create_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.create_time
	 * @param createTime  the value for member_advisory.create_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.modify_time
	 * @return  the value of member_advisory.modify_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.modify_time
	 * @param modifyTime  the value for member_advisory.modify_time
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.order_factor
	 * @return  the value of member_advisory.order_factor
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Integer getOrderFactor() {
		return orderFactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.order_factor
	 * @param orderFactor  the value for member_advisory.order_factor
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setOrderFactor(Integer orderFactor) {
		this.orderFactor = orderFactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.release_from
	 * @return  the value of member_advisory.release_from
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Long getReleaseFrom() {
		return releaseFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.release_from
	 * @param releaseFrom  the value for member_advisory.release_from
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setReleaseFrom(Long releaseFrom) {
		this.releaseFrom = releaseFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory.is_delete
	 * @return  the value of member_advisory.is_delete
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public Byte getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory.is_delete
	 * @param isDelete  the value for member_advisory.is_delete
	 * @mbggenerated  Mon May 08 16:02:34 CST 2017
	 */
	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}
}