package com.depression.model;

public class MemberAdvisoryDetail extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_detail.advisory_detail_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    /* @Comment(主键) */
    private Long advisoryDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_detail.advisory_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    /* @Comment(会员咨询外键) */
    private Long advisoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_detail.is_delete
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    /* @Comment(默认0:不删除  1：删除) */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_detail.detail
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    /* @Comment(内容) */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_detail.advisory_detail_id
     *
     * @return the value of member_advisory_detail.advisory_detail_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public Long getAdvisoryDetailId() {
        return advisoryDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_detail.advisory_detail_id
     *
     * @param advisoryDetailId the value for member_advisory_detail.advisory_detail_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public void setAdvisoryDetailId(Long advisoryDetailId) {
        this.advisoryDetailId = advisoryDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_detail.advisory_id
     *
     * @return the value of member_advisory_detail.advisory_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public Long getAdvisoryId() {
        return advisoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_detail.advisory_id
     *
     * @param advisoryId the value for member_advisory_detail.advisory_id
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public void setAdvisoryId(Long advisoryId) {
        this.advisoryId = advisoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_detail.is_delete
     *
     * @return the value of member_advisory_detail.is_delete
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_detail.is_delete
     *
     * @param isDelete the value for member_advisory_detail.is_delete
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_detail.detail
     *
     * @return the value of member_advisory_detail.detail
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_detail.detail
     *
     * @param detail the value for member_advisory_detail.detail
     *
     * @mbggenerated Sat Mar 18 16:31:01 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}