package com.depression.model;

public class MemberTag extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.tag_id
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment(主键) */
    private Long tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.hit_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment() */
    private Integer hitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.type
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment(类型) */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.ref_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment() */
    private Integer refCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.phrase
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment(短语) */
    private String phrase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.is_delete
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment(是否删除) */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tag.is_enable
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    /* @Comment() */
    private Integer isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.tag_id
     *
     * @return the value of member_tag.tag_id
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.tag_id
     *
     * @param tagId the value for member_tag.tag_id
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.hit_count
     *
     * @return the value of member_tag.hit_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Integer getHitCount() {
        return hitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.hit_count
     *
     * @param hitCount the value for member_tag.hit_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setHitCount(Integer hitCount) {
        this.hitCount = hitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.type
     *
     * @return the value of member_tag.type
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.type
     *
     * @param type the value for member_tag.type
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.ref_count
     *
     * @return the value of member_tag.ref_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Integer getRefCount() {
        return refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.ref_count
     *
     * @param refCount the value for member_tag.ref_count
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setRefCount(Integer refCount) {
        this.refCount = refCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.phrase
     *
     * @return the value of member_tag.phrase
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public String getPhrase() {
        return phrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.phrase
     *
     * @param phrase the value for member_tag.phrase
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setPhrase(String phrase) {
        this.phrase = phrase == null ? null : phrase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.is_delete
     *
     * @return the value of member_tag.is_delete
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.is_delete
     *
     * @param isDelete the value for member_tag.is_delete
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tag.is_enable
     *
     * @return the value of member_tag.is_enable
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tag.is_enable
     *
     * @param isEnable the value for member_tag.is_enable
     *
     * @mbggenerated Wed Aug 03 19:25:20 CST 2016
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }
}