package com.depression.model;

public class MessagePushMember extends Page {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_push_member.mpm_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	private Long mpmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_push_member.member_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	private Long memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_push_member.mp_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	private Long mpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_push_member.im_account
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	private String imAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_push_member.mobile_phone
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	private String mobilePhone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_push_member.mpm_id
	 * @return  the value of message_push_member.mpm_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public Long getMpmId() {
		return mpmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_push_member.mpm_id
	 * @param mpmId  the value for message_push_member.mpm_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public void setMpmId(Long mpmId) {
		this.mpmId = mpmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_push_member.member_id
	 * @return  the value of message_push_member.member_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public Long getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_push_member.member_id
	 * @param memberId  the value for message_push_member.member_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_push_member.mp_id
	 * @return  the value of message_push_member.mp_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public Long getMpId() {
		return mpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_push_member.mp_id
	 * @param mpId  the value for message_push_member.mp_id
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public void setMpId(Long mpId) {
		this.mpId = mpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_push_member.im_account
	 * @return  the value of message_push_member.im_account
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public String getImAccount() {
		return imAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_push_member.im_account
	 * @param imAccount  the value for message_push_member.im_account
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public void setImAccount(String imAccount) {
		this.imAccount = imAccount == null ? null : imAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_push_member.mobile_phone
	 * @return  the value of message_push_member.mobile_phone
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public String getMobilePhone() {
		return mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_push_member.mobile_phone
	 * @param mobilePhone  the value for message_push_member.mobile_phone
	 * @mbggenerated  Fri Mar 10 15:28:35 CST 2017
	 */
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
	}

	public MessagePushMember(Long mId, Long mpId,String imAccount) {
		super();
		this.memberId = mId;
		this.mpId = mpId;
		this.imAccount=imAccount;
	}

	public MessagePushMember() {
		super();
	}
    
}