package com.depression.model;

import java.util.Date;

public class PsychoRecommend extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.pr_id
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(主键) */
    private Long prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.mid
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(咨询师id) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.daily_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(每日固定名额) */
    private Integer dailyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.remain_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(今日剩余) */
    private Integer remainNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.create_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(创建时间) */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.update_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(更新时间) */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.is_enable
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(是否使能) */
    private Byte isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_recommend.is_delete
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    /* @Comment(是否删除) */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.pr_id
     *
     * @return the value of psycho_recommend.pr_id
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Long getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.pr_id
     *
     * @param prId the value for psycho_recommend.pr_id
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setPrId(Long prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.mid
     *
     * @return the value of psycho_recommend.mid
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.mid
     *
     * @param mid the value for psycho_recommend.mid
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.daily_number
     *
     * @return the value of psycho_recommend.daily_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Integer getDailyNumber() {
        return dailyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.daily_number
     *
     * @param dailyNumber the value for psycho_recommend.daily_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setDailyNumber(Integer dailyNumber) {
        this.dailyNumber = dailyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.remain_number
     *
     * @return the value of psycho_recommend.remain_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Integer getRemainNumber() {
        return remainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.remain_number
     *
     * @param remainNumber the value for psycho_recommend.remain_number
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setRemainNumber(Integer remainNumber) {
        this.remainNumber = remainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.create_time
     *
     * @return the value of psycho_recommend.create_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.create_time
     *
     * @param createTime the value for psycho_recommend.create_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.update_time
     *
     * @return the value of psycho_recommend.update_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.update_time
     *
     * @param updateTime the value for psycho_recommend.update_time
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.is_enable
     *
     * @return the value of psycho_recommend.is_enable
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.is_enable
     *
     * @param isEnable the value for psycho_recommend.is_enable
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_recommend.is_delete
     *
     * @return the value of psycho_recommend.is_delete
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_recommend.is_delete
     *
     * @param isDelete the value for psycho_recommend.is_delete
     *
     * @mbggenerated Fri Jun 09 16:20:18 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}