package com.depression.model;

public class TestingQuestionsOptions extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.options_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Long optionsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.questions_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Long questionsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.sequence
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Integer sequence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.title
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.score
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.opt_type
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Integer optType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.jump_to_question_no
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Integer jumpToQuestionNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.jump_result_tag
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private String jumpResultTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.is_delete
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private String isDelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_questions_options.is_enable
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	private Byte isEnable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.options_id
	 * @return  the value of testing_questions_options.options_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Long getOptionsId() {
		return optionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.options_id
	 * @param optionsId  the value for testing_questions_options.options_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setOptionsId(Long optionsId) {
		this.optionsId = optionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.questions_id
	 * @return  the value of testing_questions_options.questions_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Long getQuestionsId() {
		return questionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.questions_id
	 * @param questionsId  the value for testing_questions_options.questions_id
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setQuestionsId(Long questionsId) {
		this.questionsId = questionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.sequence
	 * @return  the value of testing_questions_options.sequence
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Integer getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.sequence
	 * @param sequence  the value for testing_questions_options.sequence
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.title
	 * @return  the value of testing_questions_options.title
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.title
	 * @param title  the value for testing_questions_options.title
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.score
	 * @return  the value of testing_questions_options.score
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.score
	 * @param score  the value for testing_questions_options.score
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.opt_type
	 * @return  the value of testing_questions_options.opt_type
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Integer getOptType() {
		return optType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.opt_type
	 * @param optType  the value for testing_questions_options.opt_type
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setOptType(Integer optType) {
		this.optType = optType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.jump_to_question_no
	 * @return  the value of testing_questions_options.jump_to_question_no
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Integer getJumpToQuestionNo() {
		return jumpToQuestionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.jump_to_question_no
	 * @param jumpToQuestionNo  the value for testing_questions_options.jump_to_question_no
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setJumpToQuestionNo(Integer jumpToQuestionNo) {
		this.jumpToQuestionNo = jumpToQuestionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.jump_result_tag
	 * @return  the value of testing_questions_options.jump_result_tag
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public String getJumpResultTag() {
		return jumpResultTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.jump_result_tag
	 * @param jumpResultTag  the value for testing_questions_options.jump_result_tag
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setJumpResultTag(String jumpResultTag) {
		this.jumpResultTag = jumpResultTag == null ? null : jumpResultTag
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.is_delete
	 * @return  the value of testing_questions_options.is_delete
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public String getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.is_delete
	 * @param isDelete  the value for testing_questions_options.is_delete
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete == null ? null : isDelete.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_questions_options.is_enable
	 * @return  the value of testing_questions_options.is_enable
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public Byte getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_questions_options.is_enable
	 * @param isEnable  the value for testing_questions_options.is_enable
	 * @mbggenerated  Tue Mar 21 11:20:59 CST 2017
	 */
	public void setIsEnable(Byte isEnable) {
		this.isEnable = isEnable;
	}
}