package com.depression.model;

import java.util.Date;

public class TestingType extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.type_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(主键) */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.parent_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(父级类别id) */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.testing_name
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(试卷类别名称) */
    private String testingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.ts_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(问卷类型：0专业测试，1趣味测试，2学生测试) */
    private Integer tsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.thumbnail
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(缩略图) */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.create_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(创建时间) */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.modify_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(修改时间) */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.is_delete
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment(默认0:不删除  1：删除) */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testing_type.is_enable
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    /* @Comment() */
    private Byte isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.type_id
     *
     * @return the value of testing_type.type_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.type_id
     *
     * @param typeId the value for testing_type.type_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.parent_id
     *
     * @return the value of testing_type.parent_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.parent_id
     *
     * @param parentId the value for testing_type.parent_id
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.testing_name
     *
     * @return the value of testing_type.testing_name
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public String getTestingName() {
        return testingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.testing_name
     *
     * @param testingName the value for testing_type.testing_name
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setTestingName(String testingName) {
        this.testingName = testingName == null ? null : testingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.ts_type
     *
     * @return the value of testing_type.ts_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Integer getTsType() {
        return tsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.ts_type
     *
     * @param tsType the value for testing_type.ts_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setTsType(Integer tsType) {
        this.tsType = tsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.thumbnail
     *
     * @return the value of testing_type.thumbnail
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.thumbnail
     *
     * @param thumbnail the value for testing_type.thumbnail
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.create_time
     *
     * @return the value of testing_type.create_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.create_time
     *
     * @param createTime the value for testing_type.create_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.modify_time
     *
     * @return the value of testing_type.modify_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.modify_time
     *
     * @param modifyTime the value for testing_type.modify_time
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.is_delete
     *
     * @return the value of testing_type.is_delete
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.is_delete
     *
     * @param isDelete the value for testing_type.is_delete
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testing_type.is_enable
     *
     * @return the value of testing_type.is_enable
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testing_type.is_enable
     *
     * @param isEnable the value for testing_type.is_enable
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }
}