package com.depression.model;

public class TestingCarouselPictures extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.cpid
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private Long cpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.type
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.descp
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private String descp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.img_path
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.testing_id
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private Long testingId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.is_enable
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private Byte isEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column testing_carousel_pictures.is_delete
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	private Byte isDelete;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.cpid
	 * @return  the value of testing_carousel_pictures.cpid
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public Long getCpid() {
		return cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.cpid
	 * @param cpid  the value for testing_carousel_pictures.cpid
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setCpid(Long cpid) {
		this.cpid = cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.type
	 * @return  the value of testing_carousel_pictures.type
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.type
	 * @param type  the value for testing_carousel_pictures.type
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.descp
	 * @return  the value of testing_carousel_pictures.descp
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public String getDescp() {
		return descp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.descp
	 * @param descp  the value for testing_carousel_pictures.descp
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setDescp(String descp) {
		this.descp = descp == null ? null : descp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.img_path
	 * @return  the value of testing_carousel_pictures.img_path
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.img_path
	 * @param imgPath  the value for testing_carousel_pictures.img_path
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.testing_id
	 * @return  the value of testing_carousel_pictures.testing_id
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public Long getTestingId() {
		return testingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.testing_id
	 * @param testingId  the value for testing_carousel_pictures.testing_id
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setTestingId(Long testingId) {
		this.testingId = testingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.is_enable
	 * @return  the value of testing_carousel_pictures.is_enable
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public Byte getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.is_enable
	 * @param isEnable  the value for testing_carousel_pictures.is_enable
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setIsEnable(Byte isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column testing_carousel_pictures.is_delete
	 * @return  the value of testing_carousel_pictures.is_delete
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public Byte getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column testing_carousel_pictures.is_delete
	 * @param isDelete  the value for testing_carousel_pictures.is_delete
	 * @mbggenerated  Wed Mar 22 14:26:36 CST 2017
	 */
	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}
}