package com.depression.model.api.dto;

import java.util.Date;
import java.util.List;

public class ApiAdvisoryCommentDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.comment_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(主键) */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.mid
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(会员id) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.advisory_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(咨询id，关联咨询表) */
    private Long advisoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.parent_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(父级回复，指向它的父结点，就是另一条回复的id) */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.ancestor_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(始祖回复是直接评论咨询本身的回复，本字段为0。由始祖回复衍生出来的回复，这个字段填始祖回复的id) */
    private Long ancestorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.praise_num
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(有用数量) */
    private Long praiseNum;
    // 0未点赞 1已点赞
    private Byte isPraised;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.comment_content
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(评论内容) */
    private String commentContent;
    
    /* @Comment(0 匿名 1不匿名) */
    private Byte isAnony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.write_location
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(发布地点) */
    private String writeLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_advisory_comment.comment_time
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    /* @Comment(创建时间) */
    private Date commentTime;
    
    private ApiMemberEssentialDTO author;
    
    private ApiAdvisoryCommentDTO parent;
    
    private List<ApiAdvisoryCommentDTO> descendants;
    
    private Integer descendantCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.comment_id
     *
     * @return the value of member_advisory_comment.comment_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.comment_id
     *
     * @param commentId the value for member_advisory_comment.comment_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.mid
     *
     * @return the value of member_advisory_comment.mid
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.mid
     *
     * @param mid the value for member_advisory_comment.mid
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.advisory_id
     *
     * @return the value of member_advisory_comment.advisory_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getAdvisoryId() {
        return advisoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.advisory_id
     *
     * @param advisoryId the value for member_advisory_comment.advisory_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setAdvisoryId(Long advisoryId) {
        this.advisoryId = advisoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.parent_id
     *
     * @return the value of member_advisory_comment.parent_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.parent_id
     *
     * @param parentId the value for member_advisory_comment.parent_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.ancestor_id
     *
     * @return the value of member_advisory_comment.ancestor_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getAncestorId() {
        return ancestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.ancestor_id
     *
     * @param ancestorId the value for member_advisory_comment.ancestor_id
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setAncestorId(Long ancestorId) {
        this.ancestorId = ancestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.praise_num
     *
     * @return the value of member_advisory_comment.praise_num
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Long getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.praise_num
     *
     * @param praiseNum the value for member_advisory_comment.praise_num
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setPraiseNum(Long praiseNum) {
        this.praiseNum = praiseNum;
    }
    
    public Byte getIsPraised()
	{
		return isPraised;
	}

	public void setIsPraised(Byte isPraised)
	{
		this.isPraised = isPraised;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.comment_content
     *
     * @return the value of member_advisory_comment.comment_content
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.comment_content
     *
     * @param commentContent the value for member_advisory_comment.comment_content
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
    
    public Byte getIsAnony()
	{
		return isAnony;
	}

	public void setIsAnony(Byte isAnony)
	{
		this.isAnony = isAnony;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.write_location
     *
     * @return the value of member_advisory_comment.write_location
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public String getWriteLocation() {
        return writeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.write_location
     *
     * @param writeLocation the value for member_advisory_comment.write_location
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setWriteLocation(String writeLocation) {
        this.writeLocation = writeLocation == null ? null : writeLocation.trim();
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_advisory_comment.comment_time
     *
     * @return the value of member_advisory_comment.comment_time
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_advisory_comment.comment_time
     *
     * @param commentTime the value for member_advisory_comment.comment_time
     *
     * @mbggenerated Mon Mar 20 19:17:16 CST 2017
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

	public ApiMemberEssentialDTO getAuthor()
	{
		return author;
	}

	public void setAuthor(ApiMemberEssentialDTO author)
	{
		this.author = author;
	}
	
	public ApiAdvisoryCommentDTO getParent()
	{
		return parent;
	}

	public void setParent(ApiAdvisoryCommentDTO parent)
	{
		this.parent = parent;
	}

	public List<ApiAdvisoryCommentDTO> getDescendants()
	{
		return descendants;
	}

	public void setDescendants(List<ApiAdvisoryCommentDTO> descendants)
	{
		this.descendants = descendants;
	}

	public Integer getDescendantCount()
	{
		return descendantCount;
	}

	public void setDescendantCount(Integer descendantCount)
	{
		this.descendantCount = descendantCount;
	}
}