package com.depression.model.api.dto;

import java.math.BigDecimal;

public class ApiCapitalPersonalAssetsDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.paid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private Long paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.account
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.mid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment(会员外键) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.cash_balance
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment(现金余额) */
    private BigDecimal cashBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.service_income_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private BigDecimal serviceIncomeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.pay_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.expense_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private BigDecimal expenseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.withdraw_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private BigDecimal withdrawAmount;
    
    private BigDecimal withdrawable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column capital_personal_assets.is_enable
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    /* @Comment() */
    private Byte isEnable;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.paid
     *
     * @return the value of capital_personal_assets.paid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public Long getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.paid
     *
     * @param paid the value for capital_personal_assets.paid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setPaid(Long paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.account
     *
     * @return the value of capital_personal_assets.account
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.account
     *
     * @param account the value for capital_personal_assets.account
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.mid
     *
     * @return the value of capital_personal_assets.mid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.mid
     *
     * @param mid the value for capital_personal_assets.mid
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.cash_balance
     *
     * @return the value of capital_personal_assets.cash_balance
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public BigDecimal getCashBalance() {
        return cashBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.cash_balance
     *
     * @param cashBalance the value for capital_personal_assets.cash_balance
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setCashBalance(BigDecimal cashBalance) {
        this.cashBalance = cashBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.service_income_amount
     *
     * @return the value of capital_personal_assets.service_income_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public BigDecimal getServiceIncomeAmount() {
        return serviceIncomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.service_income_amount
     *
     * @param serviceIncomeAmount the value for capital_personal_assets.service_income_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setServiceIncomeAmount(BigDecimal serviceIncomeAmount) {
        this.serviceIncomeAmount = serviceIncomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.pay_amount
     *
     * @return the value of capital_personal_assets.pay_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.pay_amount
     *
     * @param payAmount the value for capital_personal_assets.pay_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.expense_amount
     *
     * @return the value of capital_personal_assets.expense_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public BigDecimal getExpenseAmount() {
        return expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.expense_amount
     *
     * @param expenseAmount the value for capital_personal_assets.expense_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setExpenseAmount(BigDecimal expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.withdraw_amount
     *
     * @return the value of capital_personal_assets.withdraw_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public BigDecimal getWithdrawAmount() {
        return withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.withdraw_amount
     *
     * @param withdrawAmount the value for capital_personal_assets.withdraw_amount
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column capital_personal_assets.is_enable
     *
     * @return the value of capital_personal_assets.is_enable
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column capital_personal_assets.is_enable
     *
     * @param isEnable the value for capital_personal_assets.is_enable
     *
     * @mbggenerated Sun Aug 28 10:18:44 CST 2016
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

	public BigDecimal getWithdrawable()
	{
		return withdrawable;
	}

	public void setWithdrawable(BigDecimal withdrawable)
	{
		this.withdrawable = withdrawable;
	}
}