package com.depression.model.api.dto;

import java.util.Date;

public class ApiEvaluationLabelDTO{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluation_label.el_id
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	private Long elId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluation_label.name
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluation_label.score
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluation_label.sort_order
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	private Integer sortOrder;
	
	private Integer count;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluation_label.el_id
	 * @return  the value of evaluation_label.el_id
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public Long getElId()
	{
		return elId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluation_label.el_id
	 * @param elId  the value for evaluation_label.el_id
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public void setElId(Long elId)
	{
		this.elId = elId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluation_label.name
	 * @return  the value of evaluation_label.name
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluation_label.name
	 * @param name  the value for evaluation_label.name
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public void setName(String name)
	{
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluation_label.score
	 * @return  the value of evaluation_label.score
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public Integer getScore()
	{
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluation_label.score
	 * @param score  the value for evaluation_label.score
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public void setScore(Integer score)
	{
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluation_label.sort_order
	 * @return  the value of evaluation_label.sort_order
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public Integer getSortOrder()
	{
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluation_label.sort_order
	 * @param sortOrder  the value for evaluation_label.sort_order
	 * @mbggenerated  Sat Dec 17 16:31:49 CST 2016
	 */
	public void setSortOrder(Integer sortOrder)
	{
		this.sortOrder = sortOrder;
	}

	public Integer getCount()
	{
		return count;
	}

	public void setCount(Integer count)
	{
		this.count = count;
	}
	
}
