package com.depression.model.api.dto;

import java.util.Date;

public class ApiPsychologyContentCategoryDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psychology_content_category.pcc_id
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    /* @Comment() */
    private Long pccId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psychology_content_category.name
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    /* @Comment(名称) */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psychology_content_category.sort_order
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    /* @Comment(顺序) */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psychology_content_category.pcc_id
     *
     * @return the value of psychology_content_category.pcc_id
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public Long getPccId() {
        return pccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psychology_content_category.pcc_id
     *
     * @param pccId the value for psychology_content_category.pcc_id
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public void setPccId(Long pccId) {
        this.pccId = pccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psychology_content_category.name
     *
     * @return the value of psychology_content_category.name
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psychology_content_category.name
     *
     * @param name the value for psychology_content_category.name
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psychology_content_category.sort_order
     *
     * @return the value of psychology_content_category.sort_order
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psychology_content_category.sort_order
     *
     * @param sortOrder the value for psychology_content_category.sort_order
     *
     * @mbggenerated Thu Dec 15 16:14:39 CST 2016
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}