package com.depression.model.api.dto;

import java.util.Date;

public class ApiServiceGoodsPriceScopeDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_goods_price_scope.sgps_id
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    /* @Comment() */
    private Long sgpsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_goods_price_scope.type
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    /* @Comment(0  实时语音咨询，1 实时语音倾述) */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_goods_price_scope.floor
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    /* @Comment(下限) */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_goods_price_scope.ceiling
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    /* @Comment(上限) */
    private Integer ceiling;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_goods_price_scope.sgps_id
     *
     * @return the value of service_goods_price_scope.sgps_id
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public Long getSgpsId() {
        return sgpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_goods_price_scope.sgps_id
     *
     * @param sgpsId the value for service_goods_price_scope.sgps_id
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public void setSgpsId(Long sgpsId) {
        this.sgpsId = sgpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_goods_price_scope.type
     *
     * @return the value of service_goods_price_scope.type
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_goods_price_scope.type
     *
     * @param type the value for service_goods_price_scope.type
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_goods_price_scope.floor
     *
     * @return the value of service_goods_price_scope.floor
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_goods_price_scope.floor
     *
     * @param floor the value for service_goods_price_scope.floor
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_goods_price_scope.ceiling
     *
     * @return the value of service_goods_price_scope.ceiling
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public Integer getCeiling() {
        return ceiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_goods_price_scope.ceiling
     *
     * @param ceiling the value for service_goods_price_scope.ceiling
     *
     * @mbggenerated Thu Feb 09 11:35:59 CST 2017
     */
    public void setCeiling(Integer ceiling) {
        this.ceiling = ceiling;
    }
}