package com.depression.model.api.dto;

import java.util.Date;
import java.util.List;

public class ApiUpdateDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.update_id
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(动态id) */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.mid
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(会员id) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.content
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(内容) */
    private String content;
    
    private String detail; 

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.embrace_num
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(拥抱（点赞）数量) */
    private Long embraceNum;
    
    private Long createTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.is_anony
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(0 匿名 1不匿名) */
    private Byte isAnony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.read_count
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(阅读数) */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.write_location
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(发表位置) */
    private String writeLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_update.create_time
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    /* @Comment(创建时间) */
    private Date createTime;
    
    private Byte isEmbraced;
    
    private Integer respondCount;
    
    private ApiMemberEssentialDTO author;
    
    private List<ApiUpdateImgsDTO> imgs;
    
    private ApiUpdateCommentDTO chosenComment;
    
    private Long releaseFrom;
    
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.update_id
     *
     * @return the value of member_update.update_id
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.update_id
     *
     * @param updateId the value for member_update.update_id
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.mid
     *
     * @return the value of member_update.mid
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.mid
     *
     * @param mid the value for member_update.mid
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.content
     *
     * @return the value of member_update.content
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.content
     *
     * @param content the value for member_update.content
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getDetail()
	{
		return detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.embrace_num
     *
     * @return the value of member_update.embrace_num
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Long getEmbraceNum() {
        return embraceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.embrace_num
     *
     * @param embraceNum the value for member_update.embrace_num
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setEmbraceNum(Long embraceNum) {
        this.embraceNum = embraceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.is_anony
     *
     * @return the value of member_update.is_anony
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Byte getIsAnony() {
        return isAnony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.is_anony
     *
     * @param isAnony the value for member_update.is_anony
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setIsAnony(Byte isAnony) {
        this.isAnony = isAnony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.read_count
     *
     * @return the value of member_update.read_count
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.read_count
     *
     * @param readCount the value for member_update.read_count
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.write_location
     *
     * @return the value of member_update.write_location
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public String getWriteLocation() {
        return writeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.write_location
     *
     * @param writeLocation the value for member_update.write_location
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setWriteLocation(String writeLocation) {
        this.writeLocation = writeLocation == null ? null : writeLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_update.create_time
     *
     * @return the value of member_update.create_time
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_update.create_time
     *
     * @param createTime the value for member_update.create_time
     *
     * @mbggenerated Thu Mar 23 10:55:10 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public Byte getIsEmbraced()
	{
		return isEmbraced;
	}

	public void setIsEmbraced(Byte isEmbraced)
	{
		this.isEmbraced = isEmbraced;
	}

	public ApiMemberEssentialDTO getAuthor()
	{
		return author;
	}

	public void setAuthor(ApiMemberEssentialDTO author)
	{
		this.author = author;
	}

	public List<ApiUpdateImgsDTO> getImgs()
	{
		return imgs;
	}

	public void setImgs(List<ApiUpdateImgsDTO> imgs)
	{
		this.imgs = imgs;
	}

	public Integer getRespondCount()
	{
		return respondCount;
	}

	public void setRespondCount(Integer respondCount)
	{
		this.respondCount = respondCount;
	}

	public ApiUpdateCommentDTO getChosenComment()
	{
		return chosenComment;
	}

	public void setChosenComment(ApiUpdateCommentDTO chosenComment)
	{
		this.chosenComment = chosenComment;
	}

	public Long getReleaseFrom() {
		return releaseFrom;
	}

	public void setReleaseFrom(Long releaseFrom) {
		this.releaseFrom = releaseFrom;
	}

	public Long getCreateTimestamp() {
		return createTimestamp;
	}

	public void setCreateTimestamp(Long createTimestamp) {
		this.createTimestamp = createTimestamp;
	}
}