package com.depression.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.depression.model.Article;
import com.depression.model.ArticleCustom;
import com.github.pagehelper.Page;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	Article selectByPrimaryKey(Long articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	Article selectByPrimaryKeyLock(Long articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	List<Article> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int deleteByPrimaryKey(Long articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids,
			@Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int updateByPrimaryKey(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	List<Article> selectSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	List<Article> selectSelectiveWithPage(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 05 16:37:56 CST 2017
	 */
	int countSelective(Article record);

	/**
	 * 查询文件用户lucene更新
	 * @param lastIndexTime
	 * @param indexTime
	 * @return
	 */
	public List<Article> selectForLucene(@Param("lastIndexTime")Date lastIndexTime, 
	@Param("indexTime")Date indexTime);

	/**
	 * 查询
	 * @param ids
	 * @param pageStartNum
	 * @param pageSize
	 * @return
	 */
	public List<Article> selectByPrimaryKeysWithPageEnabled(
	@Param("ids")List<Long> ids, @Param("pageStartNum")Integer pageStartNum,
	@Param("pageSize")Integer pageSize);

	public int countByPrimaryKeysEnabled(@Param("ids")List<Long> ids);
	
	/**
	 * 根据类型名称获取最新文章
	 * @param typeName
	 * @param size
	 */
	public List<Article> getLatestByTypeName(@Param("typeName")String typeName, @Param("size")Integer size,
			@Param("isEnable")Byte isEnable);

	/**
	 * 根据类型和类别名称获取最新文章
	 * @param typeName
	 * @param categoryName
	 * @param size
	 * @return
	 */
	public List<Article> getLatestByTypeNameAndCategoryName(@Param("typeName")String typeName,
			@Param("categoryName")String categoryName, @Param("size")Integer size, @Param("isEnable")Byte isEnable);

	 /**
	  * 根据id列表获取文章列表
	  * @param ids
	  * @return
	  */
	public List<Article> getArticleByIds(@Param("ids")List<String> ids, @Param("pageStartNum")Integer pageStartNum,
			@Param("pageSize")Integer pageSize);
	public Integer countArticleByIds(@Param("ids")List<String> ids);
	
	public List<Article> searchArticleByTitle(@Param("title")String title);
	
	List<Article> selectSelectiveWithPageOrderBy(Article record);
	
	List<Article> selectSelectiveWithPageNew(Article record);

	Page<Article> searchEapArticle(@Param("eeId")Long eeId);
	
	Page<Article> searchEapAndXmArticle(@Param("eeId")Long eeId);

	public List<Article> searchArticleByTitleInEap(@Param("eeId")Long eeId, @Param("title")String title);

	Page<ArticleCustom> getArticlesByPageInEap(@Param("eeId")Long eeId, @Param("begin")Date begin, 
			@Param("end")Date end,
			@Param("words")String words, @Param("sortTag")Integer sortTag, 
			@Param("isEnable")Byte isEnable);
}