package com.depression.dao;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.depression.model.CapitalPersonalAssets;
import com.depression.model.UserType;
import com.depression.model.web.dto.CapitalPersonalAssetsDTO;

public interface CapitalPersonalAssetsMapper
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int insert(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int insertSelective(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	CapitalPersonalAssets selectByPrimaryKey(Long paid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	CapitalPersonalAssets selectByPrimaryKeyLock(Long paid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	List<CapitalPersonalAssets> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int deleteByPrimaryKey(Long paid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int updateByPrimaryKey(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int updateByPrimaryKeySelective(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	List<CapitalPersonalAssets> selectSelective(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	List<CapitalPersonalAssets> selectSelectiveWithPage(CapitalPersonalAssets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_personal_assets
	 * 
	 * @mbggenerated Sun Aug 28 10:18:44 CST 2016
	 */
	int countSelective(CapitalPersonalAssets record);

	/**
	 * 根据用户类型查找：0 用户 1 咨询师
	 * 
	 * @param userType
	 * @return
	 */
	List<CapitalPersonalAssetsDTO> selectWithPageByType(UserType userType);

	/**
	 * 根据用户类型查找数量：0 用户 1 咨询师
	 * 
	 * @param userType
	 * @return
	 */
	Integer selectWithPageByTypeCount(UserType userType);

	/**
	 * 查询咨询师资金账户列表
	 * 
	 * @param counselorCondition
	 * @return
	 */
	List<CapitalPersonalAssetsDTO> selectCounselorAccounts(@Param("userType") Integer userType, @Param("mobilePhone") String mobilePhone, @Param("account") String account,
			@Param("nickname") String nickname, @Param("title") String title, @Param("startTime") Date startTime, @Param("endTime") Date endTime, @Param("startAnswerCount") Integer startAnswerCount,
			@Param("endAnswerCount") Integer endAnswerCount, @Param("startServiceIncomeAmount") BigDecimal startServiceIncomeAmount,
			@Param("endServiceIncomeAmount") BigDecimal endServiceIncomeAmount, @Param("topNum") Integer topNum, @Param("topPercent") Integer topPercent, @Param("sortName") String sortName,
			@Param("sortType") String sortType, @Param("pageIndex") Integer pageIndex, @Param("pageSize") Integer pageSize);

	/**
	 * 查询咨询师资金账户总数
	 * 
	 * @param counselorCondition
	 * @return
	 */
	Integer selectCounselorAccountsCount(@Param("userType") Integer userType, @Param("mobilePhone") String mobilePhone, @Param("account") String account, @Param("nickname") String nickname,
			@Param("title") String title, @Param("startTime") Date startTime, @Param("endTime") Date endTime, @Param("startAnswerCount") Integer startAnswerCount,
			@Param("endAnswerCount") Integer endAnswerCount, @Param("startServiceIncomeAmount") BigDecimal startServiceIncomeAmount,
			@Param("endServiceIncomeAmount") BigDecimal endServiceIncomeAmount, @Param("topNum") Integer topNum, @Param("topPercent") Integer topPercent, @Param("sortName") String sortName,
			@Param("sortType") String sortType, @Param("pageIndex") Integer pageIndex, @Param("pageSize") Integer pageSize);

}