package com.depression.dao;

import com.depression.model.CapitalCommissionRate;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CapitalCommissionRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int insert(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int insertSelective(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    CapitalCommissionRate selectByPrimaryKey(Long crid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    CapitalCommissionRate selectByPrimaryKeyLock(Long crid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCommissionRate> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int deleteByPrimaryKey(Long crid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKey(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKeySelective(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCommissionRate> selectSelective(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCommissionRate> selectSelectiveWithPage(CapitalCommissionRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_commission_rate
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int countSelective(CapitalCommissionRate record);
}