package com.depression.dao;

import com.depression.model.CapitalCoupon;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CapitalCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int insert(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int insertSelective(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    CapitalCoupon selectByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    CapitalCoupon selectByPrimaryKeyLock(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCoupon> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int deleteByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKey(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int updateByPrimaryKeySelective(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCoupon> selectSelective(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    List<CapitalCoupon> selectSelectiveWithPage(CapitalCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_coupon
     *
     * @mbggenerated Sat Aug 27 14:35:49 CST 2016
     */
    int countSelective(CapitalCoupon record);
}