package com.depression.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.depression.model.CapitalIncomeExpenses;
import com.depression.model.MidModel;
import com.depression.model.ServiceOrder;
import com.depression.model.web.dto.CapitalIncomeExpensesDTO;
import com.depression.model.web.dto.ExpensesRecordDTO;

public interface CapitalIncomeExpensesMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int insert(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int insertSelective(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	CapitalIncomeExpenses selectByPrimaryKey(Long ieid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	CapitalIncomeExpenses selectByPrimaryKeyLock(Long ieid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	List<CapitalIncomeExpenses> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int deleteByPrimaryKey(Long ieid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int updateByPrimaryKey(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int updateByPrimaryKeySelective(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	List<CapitalIncomeExpenses> selectSelective(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	List<CapitalIncomeExpenses> selectSelectiveWithPage(CapitalIncomeExpenses record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table capital_income_expenses
	 * @mbggenerated  Wed Sep 14 14:21:36 CST 2016
	 */
	int countSelective(CapitalIncomeExpenses record);

	/**
	 * 查询现金明细根据mid，pageIndex,pageSize
	 * 
	 * @param cieVO
	 * @return
	 */
	List<CapitalIncomeExpensesDTO> selectWithPageByMid(MidModel swpbm);

	/**
	 * 查找数据根据mid
	 * 
	 * @param swpbm
	 * @return
	 */
	int selectCount(MidModel swpbm);

	/**
	 * 查询消费记录
	 * 
	 * @param swpbm
	 * @return
	 */
	List<ExpensesRecordDTO> selectWithPageExpenseRecordByMid(MidModel swpbm);

	/**
	 * 查询消费记录数量
	 * 
	 * @param swpbm
	 * @return
	 */
	int selectExpenseRecordCount(MidModel swpbm);
	
	List<CapitalIncomeExpenses> selectSelectiveOrderByTimeWithPage(CapitalIncomeExpenses record);
	
	List<String> selectDateSet();
	
	List<CapitalIncomeExpenses> selectByDay(@Param("day")String day);
}