package com.depression.dao;

import com.depression.model.EapValidEnterpriseHistory;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EapValidEnterpriseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int insert(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int insertSelective(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    EapValidEnterpriseHistory selectByPrimaryKey(Long evehId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    EapValidEnterpriseHistory selectByPrimaryKeyLock(Long evehId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    List<EapValidEnterpriseHistory> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int deleteByPrimaryKey(Long evehId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int updateByPrimaryKey(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int updateByPrimaryKeySelective(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    List<EapValidEnterpriseHistory> selectSelective(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    List<EapValidEnterpriseHistory> selectSelectiveWithPage(EapValidEnterpriseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eap_valid_enterprise_history
     *
     * @mbggenerated Tue Dec 20 18:35:07 CST 2016
     */
    int countSelective(EapValidEnterpriseHistory record);
}