package com.depression.dao;

import com.depression.model.MemberAdvisoryCurationImgs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberAdvisoryCurationImgsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int insert(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int insertSelective(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	MemberAdvisoryCurationImgs selectByPrimaryKey(Long advisoryImgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	MemberAdvisoryCurationImgs selectByPrimaryKeyLock(Long advisoryImgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	List<MemberAdvisoryCurationImgs> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int deleteByPrimaryKey(Long advisoryImgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int updateByPrimaryKey(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int updateByPrimaryKeySelective(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	List<MemberAdvisoryCurationImgs> selectSelective(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	List<MemberAdvisoryCurationImgs> selectSelectiveWithPage(MemberAdvisoryCurationImgs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_advisory_curation_imgs
	 * @mbggenerated  Sat Mar 18 16:33:50 CST 2017
	 */
	int countSelective(MemberAdvisoryCurationImgs record);
}
