package com.depression.dao;

import com.depression.model.MemberAdvisoryImgs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberAdvisoryImgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int insert(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int insertSelective(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    MemberAdvisoryImgs selectByPrimaryKey(Long advisoryImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    MemberAdvisoryImgs selectByPrimaryKeyLock(Long advisoryImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    List<MemberAdvisoryImgs> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int deleteByPrimaryKey(Long advisoryImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int updateByPrimaryKey(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int updateByPrimaryKeySelective(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    List<MemberAdvisoryImgs> selectSelective(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    List<MemberAdvisoryImgs> selectSelectiveWithPage(MemberAdvisoryImgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_advisory_imgs
     *
     * @mbggenerated Sat Mar 18 16:35:09 CST 2017
     */
    int countSelective(MemberAdvisoryImgs record);
}