package com.depression.dao;

import com.depression.model.MessagePushAdmin;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessagePushAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int insert(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int insertSelective(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    MessagePushAdmin selectByPrimaryKey(Long mpimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    MessagePushAdmin selectByPrimaryKeyLock(Long mpimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    List<MessagePushAdmin> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int deleteByPrimaryKey(Long mpimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Integer enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int updateByPrimaryKey(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int updateByPrimaryKeySelective(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    List<MessagePushAdmin> selectSelective(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    List<MessagePushAdmin> selectSelectiveWithPage(MessagePushAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_push_admin
     *
     * @mbggenerated Thu Mar 02 18:28:34 CST 2017
     */
    int countSelective(MessagePushAdmin record);
}