package com.depression.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.depression.model.PersonalityCharactersSimilarity;
import com.depression.model.web.dto.WebPersonalityCharactersSimilarityDTO;

public interface PersonalityCharactersSimilarityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int insert(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int insertSelective(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	PersonalityCharactersSimilarity selectByPrimaryKey(Long pcsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	PersonalityCharactersSimilarity selectByPrimaryKeyLock(Long pcsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	List<PersonalityCharactersSimilarity> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int deleteByPrimaryKey(Long pcsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int updateByPrimaryKey(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int updateByPrimaryKeySelective(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	List<PersonalityCharactersSimilarity> selectSelective(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	List<PersonalityCharactersSimilarity> selectSelectiveWithPage(PersonalityCharactersSimilarity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table personality_characters_similarity
	 * @mbggenerated  Thu Aug 11 11:39:44 CST 2016
	 */
	int countSelective(PersonalityCharactersSimilarity record);

	/**
     * 根据相似度倒序查询列表
     */
    List<WebPersonalityCharactersSimilarityDTO> selectSelectiveOrderBySimDesc(PersonalityCharactersSimilarity record);
}
