package com.depression.dao;

import com.depression.model.PersonalityTestMemberMapping;
import com.depression.model.web.dto.WebPersonalityTestMemberMappingDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PersonalityTestMemberMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int insert(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int insertSelective(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    PersonalityTestMemberMapping selectByPrimaryKey(Long mappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    PersonalityTestMemberMapping selectByPrimaryKeyLock(Long mappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    List<PersonalityTestMemberMapping> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int deleteByPrimaryKey(Long mappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int updateByPrimaryKey(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int updateByPrimaryKeySelective(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    List<PersonalityTestMemberMapping> selectSelective(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    List<PersonalityTestMemberMapping> selectSelectiveWithPage(PersonalityTestMemberMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personality_test_member_mapping
     *
     * @mbggenerated Thu Aug 04 14:18:29 CST 2016
     */
    int countSelective(PersonalityTestMemberMapping record);
    
    /**
     * 查询测试详细
     */
    List<WebPersonalityTestMemberMappingDTO> selectTestDetail(PersonalityTestMemberMapping record);
}
