package com.depression.dao;

import com.depression.model.PsychoGroup;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PsychoGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int insert(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int insertSelective(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    PsychoGroup selectByPrimaryKey(Long pgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    PsychoGroup selectByPrimaryKeyLock(Long pgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    List<PsychoGroup> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int deleteByPrimaryKey(Long pgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int updateByPrimaryKey(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int updateByPrimaryKeySelective(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    List<PsychoGroup> selectSelective(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    List<PsychoGroup> selectSelectiveWithPage(PsychoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psycho_group
     *
     * @mbggenerated Thu Dec 15 16:13:47 CST 2016
     */
    int countSelective(PsychoGroup record);
}