package com.depression.dao;

import com.depression.model.PushDevType;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushDevTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int insert(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int insertSelective(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    PushDevType selectByPrimaryKey(Long pushId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    PushDevType selectByPrimaryKeyLock(Long pushId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    List<PushDevType> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int deleteByPrimaryKey(Long pushId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int updateByPrimaryKey(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int updateByPrimaryKeySelective(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    List<PushDevType> selectSelective(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    List<PushDevType> selectSelectiveWithPage(PushDevType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_dev_type
     *
     * @mbggenerated Fri Feb 24 16:11:31 CST 2017
     */
    int countSelective(PushDevType record);
}