package com.depression.dao;

import com.depression.model.ServiceCallRecord;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceCallRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int insert(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int insertSelective(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	ServiceCallRecord selectByPrimaryKey(Long crId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	ServiceCallRecord selectByPrimaryKeyLock(Long crId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	List<ServiceCallRecord> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int deleteByPrimaryKey(Long crId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids,
			@Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int updateByPrimaryKey(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int updateByPrimaryKeySelective(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	List<ServiceCallRecord> selectSelective(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	List<ServiceCallRecord> selectSelectiveWithPage(ServiceCallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	int countSelective(ServiceCallRecord record);

	List<ServiceCallRecord>  selectByDate(ServiceCallRecord record);
}
