package com.depression.dao;

import com.depression.model.SystemMenu;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int insert(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int insertSelective(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	SystemMenu selectByPrimaryKey(Long menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	SystemMenu selectByPrimaryKeyLock(Long menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	List<SystemMenu> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int deleteByPrimaryKey(Long menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int updateByPrimaryKey(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int updateByPrimaryKeySelective(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	List<SystemMenu> selectSelective(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	List<SystemMenu> selectSelectiveWithPage(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbggenerated  Sat Sep 10 15:24:00 CST 2016
	 */
	int countSelective(SystemMenu record);
}
