package com.depression.dao;

import com.depression.model.TestingResultForJump;
import com.depression.model.eap.dto.TestingResultCustom;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TestingResultForJumpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int insert(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int insertSelective(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	TestingResultForJump selectByPrimaryKey(Long resId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	TestingResultForJump selectByPrimaryKeyLock(Long resId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	List<TestingResultForJump> selectByPrimaryKeyBulk(
			@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int deleteByPrimaryKey(Long resId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids,
			@Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int updateByPrimaryKey(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int updateByPrimaryKeySelective(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	List<TestingResultForJump> selectSelective(TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	List<TestingResultForJump> selectSelectiveWithPage(
			TestingResultForJump record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result_for_jump
	 * @mbggenerated  Tue Mar 21 16:34:14 CST 2017
	 */
	int countSelective(TestingResultForJump record);

	List<TestingResultCustom> getTestingResultForJumpByQuery(Map<String, Object> query);
}