package com.depression.dao;

import com.depression.model.TestingScoreAmount;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestingScoreAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int insert(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int insertSelective(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    TestingScoreAmount selectByPrimaryKey(Long scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    TestingScoreAmount selectByPrimaryKeyLock(Long scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    List<TestingScoreAmount> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int deleteByPrimaryKey(Long scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int updateByPrimaryKey(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int updateByPrimaryKeySelective(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    List<TestingScoreAmount> selectSelective(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    List<TestingScoreAmount> selectSelectiveWithPage(TestingScoreAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_score_amount
     *
     * @mbggenerated Tue Mar 21 16:47:37 CST 2017
     */
    int countSelective(TestingScoreAmount record);
}