package com.depression.dao;

import com.depression.model.TestingType;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TestingTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int insert(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int insertSelective(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    TestingType selectByPrimaryKey(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    TestingType selectByPrimaryKeyLock(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    List<TestingType> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int deleteByPrimaryKey(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int updateByPrimaryKey(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int updateByPrimaryKeySelective(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    List<TestingType> selectSelective(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    List<TestingType> selectSelectiveWithPage(TestingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testing_type
     *
     * @mbggenerated Tue Mar 21 17:38:36 CST 2017
     */
    int countSelective(TestingType record);

	void updateTestingTypeStatusByTypeIds(@Param("idList")List<Long> idList,@Param("isDel")byte isDel);

	List<TestingType> getPageList(TestingType testingType);

	Integer getPageCounts(TestingType testingType);
	
	public List<TestingType> getTestingTypeByTypeIds(List<String> classList);
}