package com.depression.dao;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.depression.model.TestingResult;
import com.depression.model.eap.dto.EapTestingDTO;
import com.depression.model.eap.dto.EapTestingResultCustom;

public interface TestingResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int insert(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int insertSelective(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	TestingResult selectByPrimaryKey(Long resultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	TestingResult selectByPrimaryKeyLock(Long resultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	List<TestingResult> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int deleteByPrimaryKey(Long resultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids,
			@Param("enable") Byte enable);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int updateByPrimaryKey(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int updateByPrimaryKeySelective(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	List<TestingResult> selectSelective(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	List<TestingResult> selectSelectiveWithPage(TestingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testing_result
	 * @mbggenerated  Wed Mar 22 16:30:43 CST 2017
	 */
	int countSelective(TestingResult record);

	void updateTestingResultDisableByIds(List<Long> resIds);

	Integer countTestingByMid(Long mid);

	List<EapTestingResultCustom> selectResultByMids(@Param("ids")List<Long> ids,@Param("pageStartNum")Integer pageStartNum,
										@Param("pageSize") Integer pageSize);

	Integer countResultByMids(@Param("ids")List<Long> ids);
}