package com.depression.model.web.dto;

import java.math.BigDecimal;
import java.util.Date;

public class WebEapEnterpriseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.ee_id
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment() */
    private Long eeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.name
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(名称) */
    private String name;
    
    /* @Comment(类型 0 学校 1企业) */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.contacts
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(联系人) */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.contacts_phone_num
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(联系人电话) */
    private String contactsPhoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.logo
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(logo) */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.logo_preview
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(logo缩略图) */
    private String logoPreview;
    
    
    /* @Comment(logo) */
    private String logoRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.logo_preview_rel
     *
     * @mbggenerated Fri Dec 16 16:00:55 CST 2016
     */
    /* @Comment(logo缩略图) */
    private String logoPreviewRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.purchased_cash_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(购买金额) */
    private BigDecimal purchasedCashAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.purchased_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(购买订单总量) */
    private Integer purchasedOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.order_single_limit
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(个人限制单数) */
    private Integer orderSingleLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.consumed_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(累计咨询单数) */
    private Integer consumedOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.consumed_duration
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(累计咨询时长) */
    private Long consumedDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.service_start_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(服务开始日期) */
    private Date serviceStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.service_end_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(服务结束日期) */
    private Date serviceEndDate;
    
    private Integer remainingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.pgid
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(服务专家组id) */
    private Long pgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.create_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment() */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.update_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment() */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.remarks
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment(备注) */
    private String remarks;
    
    /* @Comment(公告) */
    private String notice;
    //员工数量
    private Integer employeeAmount;
    
    //服务状态 0 被禁止 1未开始 2服务中 3已结束
    private Byte serviceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eap_enterprise.is_enable
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    /* @Comment() */
    private Byte isEnable;
    
    private Byte isOpened;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.ee_id
     *
     * @return the value of eap_enterprise.ee_id
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Long getEeId() {
        return eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.ee_id
     *
     * @param eeId the value for eap_enterprise.ee_id
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setEeId(Long eeId) {
        this.eeId = eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.name
     *
     * @return the value of eap_enterprise.name
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.name
     *
     * @param name the value for eap_enterprise.name
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    
    public Integer getType()
	{
		return type;
	}

	public void setType(Integer type)
	{
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.contacts
     *
     * @return the value of eap_enterprise.contacts
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.contacts
     *
     * @param contacts the value for eap_enterprise.contacts
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.contacts_phone_num
     *
     * @return the value of eap_enterprise.contacts_phone_num
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getContactsPhoneNum() {
        return contactsPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.contacts_phone_num
     *
     * @param contactsPhoneNum the value for eap_enterprise.contacts_phone_num
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setContactsPhoneNum(String contactsPhoneNum) {
        this.contactsPhoneNum = contactsPhoneNum == null ? null : contactsPhoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.logo
     *
     * @return the value of eap_enterprise.logo
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.logo
     *
     * @param logo the value for eap_enterprise.logo
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.logo_preview
     *
     * @return the value of eap_enterprise.logo_preview
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getLogoPreview() {
        return logoPreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.logo_preview
     *
     * @param logoPreview the value for eap_enterprise.logo_preview
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setLogoPreview(String logoPreview) {
        this.logoPreview = logoPreview == null ? null : logoPreview.trim();
    }
    
    public String getLogoRel()
	{
		return logoRel;
	}

	public void setLogoRel(String logoRel)
	{
		this.logoRel = logoRel;
	}

	public String getLogoPreviewRel()
	{
		return logoPreviewRel;
	}

	public void setLogoPreviewRel(String logoPreviewRel)
	{
		this.logoPreviewRel = logoPreviewRel;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.purchased_cash_amount
     *
     * @return the value of eap_enterprise.purchased_cash_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public BigDecimal getPurchasedCashAmount() {
        return purchasedCashAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.purchased_cash_amount
     *
     * @param purchasedCashAmount the value for eap_enterprise.purchased_cash_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setPurchasedCashAmount(BigDecimal purchasedCashAmount) {
        this.purchasedCashAmount = purchasedCashAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.purchased_order_amount
     *
     * @return the value of eap_enterprise.purchased_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Integer getPurchasedOrderAmount() {
        return purchasedOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.purchased_order_amount
     *
     * @param purchasedOrderAmount the value for eap_enterprise.purchased_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setPurchasedOrderAmount(Integer purchasedOrderAmount) {
        this.purchasedOrderAmount = purchasedOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.order_single_limit
     *
     * @return the value of eap_enterprise.order_single_limit
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Integer getOrderSingleLimit() {
        return orderSingleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.order_single_limit
     *
     * @param orderSingleLimit the value for eap_enterprise.order_single_limit
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setOrderSingleLimit(Integer orderSingleLimit) {
        this.orderSingleLimit = orderSingleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.consumed_order_amount
     *
     * @return the value of eap_enterprise.consumed_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Integer getConsumedOrderAmount() {
        return consumedOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.consumed_order_amount
     *
     * @param consumedOrderAmount the value for eap_enterprise.consumed_order_amount
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setConsumedOrderAmount(Integer consumedOrderAmount) {
        this.consumedOrderAmount = consumedOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.consumed_duration
     *
     * @return the value of eap_enterprise.consumed_duration
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Long getConsumedDuration() {
        return consumedDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.consumed_duration
     *
     * @param consumedDuration the value for eap_enterprise.consumed_duration
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setConsumedDuration(Long consumedDuration) {
        this.consumedDuration = consumedDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.service_start_date
     *
     * @return the value of eap_enterprise.service_start_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Date getServiceStartDate() {
        return serviceStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.service_start_date
     *
     * @param serviceStartDate the value for eap_enterprise.service_start_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setServiceStartDate(Date serviceStartDate) {
        this.serviceStartDate = serviceStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.service_end_date
     *
     * @return the value of eap_enterprise.service_end_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Date getServiceEndDate() {
        return serviceEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.service_end_date
     *
     * @param serviceEndDate the value for eap_enterprise.service_end_date
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setServiceEndDate(Date serviceEndDate) {
        this.serviceEndDate = serviceEndDate;
    }

    
    public Integer getRemainingDays()
	{
		return remainingDays;
	}

	public void setRemainingDays(Integer remainingDays)
	{
		this.remainingDays = remainingDays;
	}

    public Long getPgId()
	{
		return pgId;
	}

	public void setPgId(Long pgId)
	{
		this.pgId = pgId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.create_time
     *
     * @return the value of eap_enterprise.create_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.create_time
     *
     * @param createTime the value for eap_enterprise.create_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.update_time
     *
     * @return the value of eap_enterprise.update_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.update_time
     *
     * @param updateTime the value for eap_enterprise.update_time
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.remarks
     *
     * @return the value of eap_enterprise.remarks
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.remarks
     *
     * @param remarks the value for eap_enterprise.remarks
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
    
    public Integer getEmployeeAmount()
	{
		return employeeAmount;
	}

	public void setEmployeeAmount(Integer employeeAmount)
	{
		this.employeeAmount = employeeAmount;
	}

	public Byte getServiceStatus()
	{
		return serviceStatus;
	}

	public void setServiceStatus(Byte serviceStatus)
	{
		this.serviceStatus = serviceStatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.is_enable
     *
     * @return the value of eap_enterprise.is_enable
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.is_enable
     *
     * @param isEnable the value for eap_enterprise.is_enable
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eap_enterprise.is_enable
     *
     * @return the value of eap_enterprise.is_enable
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eap_enterprise.is_enable
     *
     * @param isEnable the value for eap_enterprise.is_enable
     *
     * @mbggenerated Thu Dec 15 16:14:09 CST 2016
     */
    public void setNotice(String notice) {
    	this.notice = notice == null ? null : notice.trim();
    }

	public Byte getIsOpened() {
		return isOpened;
	}

	public void setIsOpened(Byte isOpened) {
		this.isOpened = isOpened;
	}
}