package com.depression.model.web.dto;

import java.util.Date;

public class WebMusicClassDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.mc_id
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(主键) */
    private Long mcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.order_no
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(序号) */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.name
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(名称) */
    private String name;

    private Integer songCount;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.history_play_count
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(历史播放次数) */
    private Integer historyPlayCount;
    
    private Integer todayPlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.background_image
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(背景图) */
    private String backgroundImage;
    
    private String backgroundImageAbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.description
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(描述) */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_class.is_enable
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    /* @Comment(0启用，1禁用) */
    private Byte isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.mc_id
     *
     * @return the value of music_class.mc_id
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public Long getMcId() {
        return mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.mc_id
     *
     * @param mcId the value for music_class.mc_id
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setMcId(Long mcId) {
        this.mcId = mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.order_no
     *
     * @return the value of music_class.order_no
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.order_no
     *
     * @param orderNo the value for music_class.order_no
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.name
     *
     * @return the value of music_class.name
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.name
     *
     * @param name the value for music_class.name
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.history_play_count
     *
     * @return the value of music_class.history_play_count
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public Integer getHistoryPlayCount() {
        return historyPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.history_play_count
     *
     * @param historyPlayCount the value for music_class.history_play_count
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setHistoryPlayCount(Integer historyPlayCount) {
        this.historyPlayCount = historyPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.background_image
     *
     * @return the value of music_class.background_image
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public String getBackgroundImage() {
        return backgroundImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.background_image
     *
     * @param backgroundImage the value for music_class.background_image
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setBackgroundImage(String backgroundImage) {
        this.backgroundImage = backgroundImage == null ? null : backgroundImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.description
     *
     * @return the value of music_class.description
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.description
     *
     * @param description the value for music_class.description
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_class.is_enable
     *
     * @return the value of music_class.is_enable
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_class.is_enable
     *
     * @param isEnable the value for music_class.is_enable
     *
     * @mbggenerated Thu Mar 02 16:41:57 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

	public Integer getSongCount()
	{
		return songCount;
	}

	public void setSongCount(Integer songCount)
	{
		this.songCount = songCount;
	}

	public Integer getTodayPlayCount()
	{
		return todayPlayCount;
	}

	public void setTodayPlayCount(Integer todayPlayCount)
	{
		this.todayPlayCount = todayPlayCount;
	}

	public String getBackgroundImageAbs()
	{
		return backgroundImageAbs;
	}

	public void setBackgroundImageAbs(String backgroundImageAbs)
	{
		this.backgroundImageAbs = backgroundImageAbs;
	}
}