package com.depression.model.web.dto;

public class WebMemberAdvisoryCurationImgsDTO{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.advisory_img_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private Long advisoryImgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.ask_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private Long askId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.img_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.img_preview_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private String imgPreviewPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.is_delete
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private String isDelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_advisory_curation_imgs.is_enable
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	private String isEnable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.advisory_img_id
	 * @return  the value of member_advisory_curation_imgs.advisory_img_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public Long getAdvisoryImgId()
	{
		return advisoryImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.advisory_img_id
	 * @param advisoryImgId  the value for member_advisory_curation_imgs.advisory_img_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setAdvisoryImgId(Long advisoryImgId)
	{
		this.advisoryImgId = advisoryImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.ask_id
	 * @return  the value of member_advisory_curation_imgs.ask_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public Long getAskId()
	{
		return askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.ask_id
	 * @param askId  the value for member_advisory_curation_imgs.ask_id
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setAskId(Long askId)
	{
		this.askId = askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.img_path
	 * @return  the value of member_advisory_curation_imgs.img_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public String getImgPath()
	{
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.img_path
	 * @param imgPath  the value for member_advisory_curation_imgs.img_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setImgPath(String imgPath)
	{
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.img_preview_path
	 * @return  the value of member_advisory_curation_imgs.img_preview_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public String getImgPreviewPath()
	{
		return imgPreviewPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.img_preview_path
	 * @param imgPreviewPath  the value for member_advisory_curation_imgs.img_preview_path
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setImgPreviewPath(String imgPreviewPath)
	{
		this.imgPreviewPath = imgPreviewPath == null ? null : imgPreviewPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.is_delete
	 * @return  the value of member_advisory_curation_imgs.is_delete
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public String getIsDelete()
	{
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.is_delete
	 * @param isDelete  the value for member_advisory_curation_imgs.is_delete
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setIsDelete(String isDelete)
	{
		this.isDelete = isDelete == null ? null : isDelete.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_advisory_curation_imgs.is_enable
	 * @return  the value of member_advisory_curation_imgs.is_enable
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public String getIsEnable()
	{
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_advisory_curation_imgs.is_enable
	 * @param isEnable  the value for member_advisory_curation_imgs.is_enable
	 * @mbggenerated  Mon Oct 10 11:40:02 CST 2016
	 */
	public void setIsEnable(String isEnable)
	{
		this.isEnable = isEnable == null ? null : isEnable.trim();
	}
}