package com.depression.model.web.dto;

import java.util.Date;

public class WebMemberDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(����) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.openid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(微信入口用户使用) */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.im_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�����˺�) */
    private String imAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile_phone
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�ֻ���) */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.avatar
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(ͷ��) */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.avatar_thumbnail
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private String avatarThumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_name
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�û���) */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(����) */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birthday
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(出生日期) */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(1时是男性，2时是女性，0时是未知) */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickname
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�ǳ�) */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.hobby
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(����) */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�ȼ�) */
    private Long mLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.p_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(咨询师级别) */
    private Byte pLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.bonus_point
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(����) */
    private Long bonusPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(0 不在线，1在线，2 正在通话) */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_type
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�û�����: 1.普通会员 2. 咨询师) */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_temp
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(是否临时会员) */
    private Byte isTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reg_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(ע��ʱ��) */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(�޸�ʱ��) */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.title
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.location
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.answer_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private Integer answerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.answer_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(咨询数增量) */
    private Integer answerCountIncrement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(电话咨询增量) */
    private Integer phoneCountIncrement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.appreciated_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private Integer appreciatedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.candid_photo
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private String candidPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ltid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(执照类型id) */
    private Long ltid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_enable
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(是否有效) */
    private Byte isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.work_years
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(单位年) */
    private Byte workYears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.case_hours
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(单位小时) */
    private Integer caseHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.industry
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(行业) */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wx_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(微信号) */
    private String wxAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.profession
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(职业) */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.motto
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(铭言) */
    private String motto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.school
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(毕业学校) */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.major
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(所学专业) */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.degree
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(学历) */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.training_experience
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(培训经历) */
    private String trainingExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.signature
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(个性签名) */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.work_data_modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(从业数据修改时间) */
    private Date workDataModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.primary_domain
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(擅长领域) */
    private String primaryDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.photo_certification_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(处理过的资格证照) */
    private String photoCertificationDealtRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(处理过的资格证照预览) */
    private String photoCertificationDealtPreviewRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.photo_identity_card_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(处理过的身份证照) */
    private String photoIdentityCardDealtRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment(处理过的身份证照预览) */
    private String photoIdentityCardDealtPreviewRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.profile
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    /* @Comment() */
    private String profile;
    
    /**禁言天数*/
    private Integer disableMessageDays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mid
     *
     * @return the value of member.mid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mid
     *
     * @param mid the value for member.mid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.openid
     *
     * @return the value of member.openid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.openid
     *
     * @param openid the value for member.openid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.im_account
     *
     * @return the value of member.im_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getImAccount() {
        return imAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.im_account
     *
     * @param imAccount the value for member.im_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setImAccount(String imAccount) {
        this.imAccount = imAccount == null ? null : imAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile_phone
     *
     * @return the value of member.mobile_phone
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile_phone
     *
     * @param mobilePhone the value for member.mobile_phone
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.avatar
     *
     * @return the value of member.avatar
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.avatar
     *
     * @param avatar the value for member.avatar
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.avatar_thumbnail
     *
     * @return the value of member.avatar_thumbnail
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getAvatarThumbnail() {
        return avatarThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.avatar_thumbnail
     *
     * @param avatarThumbnail the value for member.avatar_thumbnail
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setAvatarThumbnail(String avatarThumbnail) {
        this.avatarThumbnail = avatarThumbnail == null ? null : avatarThumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_name
     *
     * @return the value of member.user_name
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_name
     *
     * @param userName the value for member.user_name
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birthday
     *
     * @return the value of member.birthday
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birthday
     *
     * @param birthday the value for member.birthday
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.hobby
     *
     * @return the value of member.hobby
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.hobby
     *
     * @param hobby the value for member.hobby
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_level
     *
     * @return the value of member.m_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Long getmLevel() {
        return mLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_level
     *
     * @param mLevel the value for member.m_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setmLevel(Long mLevel) {
        this.mLevel = mLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.p_level
     *
     * @return the value of member.p_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getpLevel() {
        return pLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.p_level
     *
     * @param pLevel the value for member.p_level
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setpLevel(Byte pLevel) {
        this.pLevel = pLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.bonus_point
     *
     * @return the value of member.bonus_point
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Long getBonusPoint() {
        return bonusPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.bonus_point
     *
     * @param bonusPoint the value for member.bonus_point
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setBonusPoint(Long bonusPoint) {
        this.bonusPoint = bonusPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_type
     *
     * @return the value of member.user_type
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_type
     *
     * @param userType the value for member.user_type
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_temp
     *
     * @return the value of member.is_temp
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getIsTemp() {
        return isTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_temp
     *
     * @param isTemp the value for member.is_temp
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setIsTemp(Byte isTemp) {
        this.isTemp = isTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reg_time
     *
     * @return the value of member.reg_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reg_time
     *
     * @param regTime the value for member.reg_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.modify_time
     *
     * @return the value of member.modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.modify_time
     *
     * @param modifyTime the value for member.modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.title
     *
     * @return the value of member.title
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.title
     *
     * @param title the value for member.title
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.location
     *
     * @return the value of member.location
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.location
     *
     * @param location the value for member.location
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.answer_count
     *
     * @return the value of member.answer_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Integer getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.answer_count
     *
     * @param answerCount the value for member.answer_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.answer_count_increment
     *
     * @return the value of member.answer_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Integer getAnswerCountIncrement() {
        return answerCountIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.answer_count_increment
     *
     * @param answerCountIncrement the value for member.answer_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setAnswerCountIncrement(Integer answerCountIncrement) {
        this.answerCountIncrement = answerCountIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone_count_increment
     *
     * @return the value of member.phone_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Integer getPhoneCountIncrement() {
        return phoneCountIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone_count_increment
     *
     * @param phoneCountIncrement the value for member.phone_count_increment
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPhoneCountIncrement(Integer phoneCountIncrement) {
        this.phoneCountIncrement = phoneCountIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.appreciated_count
     *
     * @return the value of member.appreciated_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Integer getAppreciatedCount() {
        return appreciatedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.appreciated_count
     *
     * @param appreciatedCount the value for member.appreciated_count
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setAppreciatedCount(Integer appreciatedCount) {
        this.appreciatedCount = appreciatedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.candid_photo
     *
     * @return the value of member.candid_photo
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getCandidPhoto() {
        return candidPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.candid_photo
     *
     * @param candidPhoto the value for member.candid_photo
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setCandidPhoto(String candidPhoto) {
        this.candidPhoto = candidPhoto == null ? null : candidPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ltid
     *
     * @return the value of member.ltid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Long getLtid() {
        return ltid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ltid
     *
     * @param ltid the value for member.ltid
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setLtid(Long ltid) {
        this.ltid = ltid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_enable
     *
     * @return the value of member.is_enable
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_enable
     *
     * @param isEnable the value for member.is_enable
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.work_years
     *
     * @return the value of member.work_years
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Byte getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.work_years
     *
     * @param workYears the value for member.work_years
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setWorkYears(Byte workYears) {
        this.workYears = workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.case_hours
     *
     * @return the value of member.case_hours
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Integer getCaseHours() {
        return caseHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.case_hours
     *
     * @param caseHours the value for member.case_hours
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setCaseHours(Integer caseHours) {
        this.caseHours = caseHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.industry
     *
     * @return the value of member.industry
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.industry
     *
     * @param industry the value for member.industry
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wx_account
     *
     * @return the value of member.wx_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getWxAccount() {
        return wxAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wx_account
     *
     * @param wxAccount the value for member.wx_account
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setWxAccount(String wxAccount) {
        this.wxAccount = wxAccount == null ? null : wxAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.profession
     *
     * @return the value of member.profession
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.profession
     *
     * @param profession the value for member.profession
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.motto
     *
     * @return the value of member.motto
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.motto
     *
     * @param motto the value for member.motto
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.school
     *
     * @return the value of member.school
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.school
     *
     * @param school the value for member.school
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.major
     *
     * @return the value of member.major
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.major
     *
     * @param major the value for member.major
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.degree
     *
     * @return the value of member.degree
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.degree
     *
     * @param degree the value for member.degree
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.training_experience
     *
     * @return the value of member.training_experience
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getTrainingExperience() {
        return trainingExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.training_experience
     *
     * @param trainingExperience the value for member.training_experience
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setTrainingExperience(String trainingExperience) {
        this.trainingExperience = trainingExperience == null ? null : trainingExperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.signature
     *
     * @return the value of member.signature
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.signature
     *
     * @param signature the value for member.signature
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.work_data_modify_time
     *
     * @return the value of member.work_data_modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public Date getWorkDataModifyTime() {
        return workDataModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.work_data_modify_time
     *
     * @param workDataModifyTime the value for member.work_data_modify_time
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setWorkDataModifyTime(Date workDataModifyTime) {
        this.workDataModifyTime = workDataModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.primary_domain
     *
     * @return the value of member.primary_domain
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getPrimaryDomain() {
        return primaryDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.primary_domain
     *
     * @param primaryDomain the value for member.primary_domain
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPrimaryDomain(String primaryDomain) {
        this.primaryDomain = primaryDomain == null ? null : primaryDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.photo_certification_dealt_rel
     *
     * @return the value of member.photo_certification_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getPhotoCertificationDealtRel() {
        return photoCertificationDealtRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.photo_certification_dealt_rel
     *
     * @param photoCertificationDealtRel the value for member.photo_certification_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPhotoCertificationDealtRel(String photoCertificationDealtRel) {
        this.photoCertificationDealtRel = photoCertificationDealtRel == null ? null : photoCertificationDealtRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.photo_certification_dealt_preview_rel
     *
     * @return the value of member.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getPhotoCertificationDealtPreviewRel() {
        return photoCertificationDealtPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.photo_certification_dealt_preview_rel
     *
     * @param photoCertificationDealtPreviewRel the value for member.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPhotoCertificationDealtPreviewRel(String photoCertificationDealtPreviewRel) {
        this.photoCertificationDealtPreviewRel = photoCertificationDealtPreviewRel == null ? null : photoCertificationDealtPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.photo_identity_card_dealt_rel
     *
     * @return the value of member.photo_identity_card_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getPhotoIdentityCardDealtRel() {
        return photoIdentityCardDealtRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.photo_identity_card_dealt_rel
     *
     * @param photoIdentityCardDealtRel the value for member.photo_identity_card_dealt_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPhotoIdentityCardDealtRel(String photoIdentityCardDealtRel) {
        this.photoIdentityCardDealtRel = photoIdentityCardDealtRel == null ? null : photoIdentityCardDealtRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.photo_identity_card_dealt_preview_rel
     *
     * @return the value of member.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getPhotoIdentityCardDealtPreviewRel() {
        return photoIdentityCardDealtPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.photo_identity_card_dealt_preview_rel
     *
     * @param photoIdentityCardDealtPreviewRel the value for member.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setPhotoIdentityCardDealtPreviewRel(String photoIdentityCardDealtPreviewRel) {
        this.photoIdentityCardDealtPreviewRel = photoIdentityCardDealtPreviewRel == null ? null : photoIdentityCardDealtPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.profile
     *
     * @return the value of member.profile
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.profile
     *
     * @param profile the value for member.profile
     *
     * @mbggenerated Thu Feb 09 17:04:55 CST 2017
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

	public Integer getDisableMessageDays()
	{
		return disableMessageDays;
	}

	public void setDisableMessageDays(Integer disableMessageDays)
	{
		this.disableMessageDays = disableMessageDays;
	}
    
    
}