package com.depression.model.web.dto;

import java.util.Date;

public class WebPsychoInfoDTO{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.piid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(主键) */
    private Long piid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.ltid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private Long ltid;
    
    private String licenseName;
    
    private String[] primaryDomains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.mid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(主键) */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.name
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(姓名) */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.sex
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(0 男 1女 2未知) */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.mobile_phone
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(手机号) */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.wx_account
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(微信号) */
    private String wxAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.location
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(所在地) */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.title
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String title;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.work_years
    *
    * @mbggenerated Thu Dec 08 10:00:02 CST 2016
    */
   /* @Comment(单位年) */
   private Byte workYears;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.case_hours
    *
    * @mbggenerated Thu Dec 08 10:00:02 CST 2016
    */
   /* @Comment(单位小时) */
   private Integer caseHours;
   
   /* @Comment(咨询师级别) */
   private Byte pLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_certification_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCertificationDealtRel;
    
    private String photoCertificationDealt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCertificationDealtPreviewRel;
    
    private String photoCertificationDealtPreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_certification_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCertificationRel;
    
    private String photoCertification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_certification_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCertificationPreviewRel;
    
    private String photoCertificationPreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_identity_card_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoIdentityCardDealtRel;
    
    private String photoIdentityCardDealt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoIdentityCardDealtPreviewRel;
    
    private String photoIdentityCardDealtPreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_identity_card_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoIdentityCardRel;

    private String photoIdentityCard;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_identity_card_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoIdentityCardPreviewRel;

    private String photoIdentityCardPreview;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_candid_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCandidRel;

    private String photoCandid;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.photo_candid_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String photoCandidPreviewRel;

    private String photoCandidPreview;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.photo_candid_dealt_rel
    *
    * @mbggenerated Tue Sep 13 13:18:02 CST 2016
    */
   /* @Comment() */
   private String photoCandidDealtRel;
   private String photoCandidDealt;
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.photo_candid_dealt_preview_rel
    *
    * @mbggenerated Tue Sep 13 13:18:02 CST 2016
    */
   /* @Comment() */
   private String photoCandidDealtPreviewRel;
   private String photoCandidDealtPreview;
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.photo_avatar_rel
    *
    * @mbggenerated Tue Sep 13 13:18:02 CST 2016
    */
   /* @Comment() */
   private String photoAvatarRel;
   private String photoAvatar;
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column psycho_info.photo_avatar_preview_rel
    *
    * @mbggenerated Tue Sep 13 13:18:02 CST 2016
    */
   /* @Comment() */
   private String photoAvatarPreviewRel;
   private String photoAvatarPreview;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.brief
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String brief;
    
    /* @Comment(信息来源) */
    private String infoChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.referrer
     *
     * @mbggenerated Thu Apr 13 13:06:42 CST 2017
     */
    /* @Comment(推荐人) */
    private String referrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.referrer_wechat
     *
     * @mbggenerated Thu Apr 13 13:06:42 CST 2017
     */
    /* @Comment(推荐人微信) */
    private String referrerWechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.audit_status
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment(0 未审核， 1 审核通过， 2审核不通过) */
    private Byte auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.nogo_reason
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private String nogoReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.create_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.audit_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psycho_info.is_enable
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    /* @Comment() */
    private Byte isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.piid
     *
     * @return the value of psycho_info.piid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Long getPiid() {
        return piid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.piid
     *
     * @param piid the value for psycho_info.piid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPiid(Long piid) {
        this.piid = piid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.ltid
     *
     * @return the value of psycho_info.ltid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Long getLtid() {
        return ltid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.ltid
     *
     * @param ltid the value for psycho_info.ltid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setLtid(Long ltid) {
        this.ltid = ltid;
    }

	public String getLicenseName()
	{
		return licenseName;
	}

	public void setLicenseName(String licenseName)
	{
		this.licenseName = licenseName;
	}

	public String[] getPrimaryDomains()
	{
		return primaryDomains;
	}

	public void setPrimaryDomains(String[] primaryDomains)
	{
		this.primaryDomains = primaryDomains;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.mid
     *
     * @return the value of psycho_info.mid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.mid
     *
     * @param mid the value for psycho_info.mid
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.name
     *
     * @return the value of psycho_info.name
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.name
     *
     * @param name the value for psycho_info.name
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.sex
     *
     * @return the value of psycho_info.sex
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.sex
     *
     * @param sex the value for psycho_info.sex
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.mobile_phone
     *
     * @return the value of psycho_info.mobile_phone
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.mobile_phone
     *
     * @param mobilePhone the value for psycho_info.mobile_phone
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.wx_account
     *
     * @return the value of psycho_info.wx_account
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getWxAccount() {
        return wxAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.wx_account
     *
     * @param wxAccount the value for psycho_info.wx_account
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setWxAccount(String wxAccount) {
        this.wxAccount = wxAccount == null ? null : wxAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.location
     *
     * @return the value of psycho_info.location
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.location
     *
     * @param location the value for psycho_info.location
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.title
     *
     * @return the value of psycho_info.title
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.title
     *
     * @param title the value for psycho_info.title
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
    
    

    public Byte getWorkYears()
	{
		return workYears;
	}

	public void setWorkYears(Byte workYears)
	{
		this.workYears = workYears;
	}

	public Integer getCaseHours()
	{
		return caseHours;
	}

	public void setCaseHours(Integer caseHours)
	{
		this.caseHours = caseHours;
	}

	public Byte getpLevel()
	{
		return pLevel;
	}

	public void setpLevel(Byte pLevel)
	{
		this.pLevel = pLevel;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_certification_dealt_rel
     *
     * @return the value of psycho_info.photo_certification_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCertificationDealtRel() {
        return photoCertificationDealtRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_certification_dealt_rel
     *
     * @param photoCertificationDealtRel the value for psycho_info.photo_certification_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCertificationDealtRel(String photoCertificationDealtRel) {
        this.photoCertificationDealtRel = photoCertificationDealtRel == null ? null : photoCertificationDealtRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_certification_dealt_preview_rel
     *
     * @return the value of psycho_info.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCertificationDealtPreviewRel() {
        return photoCertificationDealtPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_certification_dealt_preview_rel
     *
     * @param photoCertificationDealtPreviewRel the value for psycho_info.photo_certification_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCertificationDealtPreviewRel(String photoCertificationDealtPreviewRel) {
        this.photoCertificationDealtPreviewRel = photoCertificationDealtPreviewRel == null ? null : photoCertificationDealtPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_certification_rel
     *
     * @return the value of psycho_info.photo_certification_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCertificationRel() {
        return photoCertificationRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_certification_rel
     *
     * @param photoCertificationRel the value for psycho_info.photo_certification_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCertificationRel(String photoCertificationRel) {
        this.photoCertificationRel = photoCertificationRel == null ? null : photoCertificationRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_certification_preview_rel
     *
     * @return the value of psycho_info.photo_certification_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCertificationPreviewRel() {
        return photoCertificationPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_certification_preview_rel
     *
     * @param photoCertificationPreviewRel the value for psycho_info.photo_certification_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCertificationPreviewRel(String photoCertificationPreviewRel) {
        this.photoCertificationPreviewRel = photoCertificationPreviewRel == null ? null : photoCertificationPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_identity_card_dealt_rel
     *
     * @return the value of psycho_info.photo_identity_card_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoIdentityCardDealtRel() {
        return photoIdentityCardDealtRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_identity_card_dealt_rel
     *
     * @param photoIdentityCardDealtRel the value for psycho_info.photo_identity_card_dealt_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoIdentityCardDealtRel(String photoIdentityCardDealtRel) {
        this.photoIdentityCardDealtRel = photoIdentityCardDealtRel == null ? null : photoIdentityCardDealtRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_identity_card_dealt_preview_rel
     *
     * @return the value of psycho_info.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoIdentityCardDealtPreviewRel() {
        return photoIdentityCardDealtPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_identity_card_dealt_preview_rel
     *
     * @param photoIdentityCardDealtPreviewRel the value for psycho_info.photo_identity_card_dealt_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoIdentityCardDealtPreviewRel(String photoIdentityCardDealtPreviewRel) {
        this.photoIdentityCardDealtPreviewRel = photoIdentityCardDealtPreviewRel == null ? null : photoIdentityCardDealtPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_identity_card_rel
     *
     * @return the value of psycho_info.photo_identity_card_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoIdentityCardRel() {
        return photoIdentityCardRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_identity_card_rel
     *
     * @param photoIdentityCardRel the value for psycho_info.photo_identity_card_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoIdentityCardRel(String photoIdentityCardRel) {
        this.photoIdentityCardRel = photoIdentityCardRel == null ? null : photoIdentityCardRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_identity_card_preview_rel
     *
     * @return the value of psycho_info.photo_identity_card_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoIdentityCardPreviewRel() {
        return photoIdentityCardPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_identity_card_preview_rel
     *
     * @param photoIdentityCardPreviewRel the value for psycho_info.photo_identity_card_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoIdentityCardPreviewRel(String photoIdentityCardPreviewRel) {
        this.photoIdentityCardPreviewRel = photoIdentityCardPreviewRel == null ? null : photoIdentityCardPreviewRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_candid_rel
     *
     * @return the value of psycho_info.photo_candid_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCandidRel() {
        return photoCandidRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_candid_rel
     *
     * @param photoCandidRel the value for psycho_info.photo_candid_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCandidRel(String photoCandidRel) {
        this.photoCandidRel = photoCandidRel == null ? null : photoCandidRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.photo_candid_preview_rel
     *
     * @return the value of psycho_info.photo_candid_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getPhotoCandidPreviewRel() {
        return photoCandidPreviewRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.photo_candid_preview_rel
     *
     * @param photoCandidPreviewRel the value for psycho_info.photo_candid_preview_rel
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setPhotoCandidPreviewRel(String photoCandidPreviewRel) {
        this.photoCandidPreviewRel = photoCandidPreviewRel == null ? null : photoCandidPreviewRel.trim();
    }

    public String getPhotoCandidDealtRel()
	{
		return photoCandidDealtRel;
	}

	public void setPhotoCandidDealtRel(String photoCandidDealtRel)
	{
		this.photoCandidDealtRel = photoCandidDealtRel;
	}

	public String getPhotoCandidDealt()
	{
		return photoCandidDealt;
	}

	public void setPhotoCandidDealt(String photoCandidDealt)
	{
		this.photoCandidDealt = photoCandidDealt;
	}

	public String getPhotoCandidDealtPreviewRel()
	{
		return photoCandidDealtPreviewRel;
	}

	public void setPhotoCandidDealtPreviewRel(String photoCandidDealtPreviewRel)
	{
		this.photoCandidDealtPreviewRel = photoCandidDealtPreviewRel;
	}

	public String getPhotoCandidDealtPreview()
	{
		return photoCandidDealtPreview;
	}

	public void setPhotoCandidDealtPreview(String photoCandidDealtPreview)
	{
		this.photoCandidDealtPreview = photoCandidDealtPreview;
	}

	public String getPhotoAvatarRel()
	{
		return photoAvatarRel;
	}

	public void setPhotoAvatarRel(String photoAvatarRel)
	{
		this.photoAvatarRel = photoAvatarRel;
	}

	public String getPhotoAvatar()
	{
		return photoAvatar;
	}

	public void setPhotoAvatar(String photoAvatar)
	{
		this.photoAvatar = photoAvatar;
	}

	public String getPhotoAvatarPreviewRel()
	{
		return photoAvatarPreviewRel;
	}

	public void setPhotoAvatarPreviewRel(String photoAvatarPreviewRel)
	{
		this.photoAvatarPreviewRel = photoAvatarPreviewRel;
	}

	public String getPhotoAvatarPreview()
	{
		return photoAvatarPreview;
	}

	public void setPhotoAvatarPreview(String photoAvatarPreview)
	{
		this.photoAvatarPreview = photoAvatarPreview;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.brief
     *
     * @return the value of psycho_info.brief
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.brief
     *
     * @param brief the value for psycho_info.brief
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    public String getInfoChannel()
	{
		return infoChannel;
	}

	public void setInfoChannel(String infoChannel)
	{
		this.infoChannel = infoChannel;
	}

	public String getReferrer()
	{
		return referrer;
	}

	public void setReferrer(String referrer)
	{
		this.referrer = referrer;
	}

	public String getReferrerWechat()
	{
		return referrerWechat;
	}

	public void setReferrerWechat(String referrerWechat)
	{
		this.referrerWechat = referrerWechat;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.audit_status
     *
     * @return the value of psycho_info.audit_status
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.audit_status
     *
     * @param auditStatus the value for psycho_info.audit_status
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.nogo_reason
     *
     * @return the value of psycho_info.nogo_reason
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public String getNogoReason() {
        return nogoReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.nogo_reason
     *
     * @param nogoReason the value for psycho_info.nogo_reason
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setNogoReason(String nogoReason) {
        this.nogoReason = nogoReason == null ? null : nogoReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.create_time
     *
     * @return the value of psycho_info.create_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.create_time
     *
     * @param createTime the value for psycho_info.create_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.audit_time
     *
     * @return the value of psycho_info.audit_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.audit_time
     *
     * @param auditTime the value for psycho_info.audit_time
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psycho_info.is_enable
     *
     * @return the value of psycho_info.is_enable
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psycho_info.is_enable
     *
     * @param isEnable the value for psycho_info.is_enable
     *
     * @mbggenerated Mon Sep 12 18:23:05 CST 2016
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

	public String getPhotoCertificationDealt()
	{
		return photoCertificationDealt;
	}

	public void setPhotoCertificationDealt(String photoCertificationDealt)
	{
		this.photoCertificationDealt = photoCertificationDealt;
	}

	public String getPhotoCertificationDealtPreview()
	{
		return photoCertificationDealtPreview;
	}

	public void setPhotoCertificationDealtPreview(String photoCertificationDealtPreview)
	{
		this.photoCertificationDealtPreview = photoCertificationDealtPreview;
	}

	public String getPhotoCertification()
	{
		return photoCertification;
	}

	public void setPhotoCertification(String photoCertification)
	{
		this.photoCertification = photoCertification;
	}

	public String getPhotoCertificationPreview()
	{
		return photoCertificationPreview;
	}

	public void setPhotoCertificationPreview(String photoCertificationPreview)
	{
		this.photoCertificationPreview = photoCertificationPreview;
	}

	public String getPhotoIdentityCardDealt()
	{
		return photoIdentityCardDealt;
	}

	public void setPhotoIdentityCardDealt(String photoIdentityCardDealt)
	{
		this.photoIdentityCardDealt = photoIdentityCardDealt;
	}

	public String getPhotoIdentityCardDealtPreview()
	{
		return photoIdentityCardDealtPreview;
	}

	public void setPhotoIdentityCardDealtPreview(String photoIdentityCardDealtPreview)
	{
		this.photoIdentityCardDealtPreview = photoIdentityCardDealtPreview;
	}

	public String getPhotoIdentityCard()
	{
		return photoIdentityCard;
	}

	public void setPhotoIdentityCard(String photoIdentityCard)
	{
		this.photoIdentityCard = photoIdentityCard;
	}

	public String getPhotoIdentityCardPreview()
	{
		return photoIdentityCardPreview;
	}

	public void setPhotoIdentityCardPreview(String photoIdentityCardPreview)
	{
		this.photoIdentityCardPreview = photoIdentityCardPreview;
	}

	public String getPhotoCandid()
	{
		return photoCandid;
	}

	public void setPhotoCandid(String photoCandid)
	{
		this.photoCandid = photoCandid;
	}

	public String getPhotoCandidPreview()
	{
		return photoCandidPreview;
	}

	public void setPhotoCandidPreview(String photoCandidPreview)
	{
		this.photoCandidPreview = photoCandidPreview;
	}
}